before_script:
    - apt update
    - apt install -y python3
    - python3 -V
    - uname -a

unittest:
    image: debian:stretch
    stage: test
    script:
    - apt update
    - apt install -y sqlite3 locales-all python3-flask python3-ldap3 python3-requests python3-pillow python3-coverage
    - python3 -m coverage run tests.py
    - python3 -m coverage report --include "./*"
    - python3 -m coverage report -m  --include "./*" > report.txt
    - python3 -m coverage html --include "./*"
    artifacts:
        paths:
        - htmlcov/*
        - .coverage
        - report.txt
